apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce # k3s nepodporuje ReadWriteMany. ReadWriteOnce je dostatočné pre naše účely pretože obmedzuje len prístup z jedného node. Viaceré pody môžu stále pristupovať.
  resources:
    requests:
      storage: {{ .Values.storage.cache.size }}
  storageClassName: {{ .Values.storage.cache.storageClass }}