apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-cache-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard 
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-pipelines-trigger-auth
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: azure-pat-token
      key: AZURE_PAT_TOKEN
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: build-agent-config-{{ .Values.pool.agentNameBase }}
data:
  AZP_URL: "https://dev.azure.com/krossk"
  AzurePS: "3.0.1"
  AZP_POOL: {{ .Values.pool.name | quote }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.pool.agentNameBase }}
  labels:
    app: build-agent-{{ .Values.pool.agentNameBase }}-statefulset
    pool: {{ .Values.pool.agentNameBase }}
spec:
  serviceName: "{{ .Values.pool.agentNameBase }}-service"
  replicas: {{ .Values.pool.replicas }}
  ordinals:
    start: 1
  selector:
    matchLabels:
      app: build-agent-{{ .Values.pool.agentNameBase }}
      pool: {{ .Values.pool.agentNameBase }}
  template:
    metadata:
      labels:
        app: build-agent-{{ .Values.pool.agentNameBase }}
        pool: {{ .Values.pool.agentNameBase }}
    spec:
      containers:
      - name: "{{ .Values.pool.agentNameBase }}-container"
        image: "{{ .Values.pool.image.name }}:{{ .Values.pool.image.tag }}"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: AZP_AGENT_NAME
          value: "$(POD_NAME)-build4"
        - name: KUBECONFIG
          value: "/opt/Agents/$(AZP_AGENT_NAME)/kubeconfig"
        - name: DEVEXTREME_KEY
          valueFrom:
            secretKeyRef:
              name: devextreme-key
              key: DEVEXTREME_KEY
        - name: AZURE_PAT_TOKEN
          valueFrom:
            secretKeyRef:
              name: azure-pat-token
              key: AZURE_PAT_TOKEN
        envFrom:
        - configMapRef:
            name: build-agent-config-{{ .Values.pool.agentNameBase }}
        volumeMounts:
        - name: agent-cache
          mountPath: /opt/Agents/cache
      volumes:
      - name: agent-cache
        persistentVolumeClaim:
          claimName: agent-cache-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.pool.agentNameBase }}-service"
spec:
  clusterIP: None
  selector:
    app: build-agent-{{ .Values.pool.agentNameBase }}
    pool: {{ .Values.pool.agentNameBase }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: "{{ .Values.pool.agentNameBase }}-scaled-object"
spec:
  scaleTargetRef:
    name: {{ .Values.pool.agentNameBase }}
    kind: StatefulSet
  pollingInterval: {{ .Values.pool.scaler.pollingInterval }}
  cooldownPeriod: {{ .Values.pool.scaler.cooldownPeriod }}
  minReplicaCount: {{ .Values.pool.scaler.minReplicas }}
  maxReplicaCount: {{ .Values.pool.scaler.maxReplicas }}
  triggers:
  - type: azure-pipelines
    metadata:
      poolName: {{ .Values.pool.name | quote }}
      organizationURLFromEnv: "AZP_URL"
      targetPipelinesQueueLength: {{ .Values.pool.scaler.targetPipelinesQueueLength | quote }}
    authenticationRef:
      name: azure-pipelines-trigger-auth