apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: "{{ .Values.pool.agentNameBase }}-trigger-auth"
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: azure-pat-token
      key: AZURE_PAT_TOKEN 