version: '3.8'

services:
  build-fe-01-docker:
    image: azure-agent-linux:latest
    environment:
      - AZP_URL=https://dev.azure.com/krossk
      - AZP_AGENT_NAME=build-fe-01-docker
      - AZP_POOL=Build FE
      - KUBECONFIG=/opt/Agents/build-fe-01-docker/kubeconfig
      - DEVEXTREME_KEY=${DEVEXTREME_KEY}
      - AzurePS=3.0.1
    volumes:
      #- /opt/Agents/build-fe-01-docker:/opt/Agents/build-fe-01-docker # Ak by sme potrebovali uchovavat workspaces aj po ukonceni kontajneru.
      - /opt/Agents/cache:/opt/Agents/cache
    secrets:
      - azure_pat_token
    deploy:
      restart_policy:
        condition: any
  
  build-fe-02-docker:
    image: azure-agent-linux:latest
    environment:
      - AZP_URL=https://dev.azure.com/krossk
      - AZP_AGENT_NAME=build-fe-02-docker
      - AZP_POOL=Build FE
      - KUBECONFIG=/opt/Agents/build-fe-02-docker/kubeconfig
      - DEVEXTREME_KEY=${DEVEXTREME_KEY}
      - AzurePS=3.0.1
    volumes:
      #- /opt/Agents/build-fe-02-docker:/opt/Agents/build-fe-02-docker # Ak by sme potrebovali uchovavat workspaces aj po ukonceni kontajneru.
      - /opt/Agents/cache:/opt/Agents/cache
    secrets:
      - azure_pat_token
    deploy:
      restart_policy:
        condition: any

  build-fe-03-docker:
    image: azure-agent-linux:latest
    environment:
      - AZP_URL=https://dev.azure.com/krossk
      - AZP_AGENT_NAME=build-fe-03-docker
      - AZP_POOL=Build FE
      - KUBECONFIG=/opt/Agents/build-fe-03-docker/kubeconfig
      - DEVEXTREME_KEY=${DEVEXTREME_KEY}
      - AzurePS=3.0.1
    volumes:
      #- /opt/Agents/build-fe-03-docker:/opt/Agents/build-fe-03-docker # Ak by sme potrebovali uchovavat workspaces aj po ukonceni kontajneru.
      - /opt/Agents/cache:/opt/Agents/cache
    secrets:
      - azure_pat_token
    deploy:
      restart_policy:
        condition: any

secrets:
  azure_pat_token:
    external: true 
