version: '3.8'

services:
  agent1:
    build:
      context: .
      dockerfile: azure-agent-linux.dockerfile
    environment:
      - AZP_URL=https://dev.azure.com/krossk
      - AZP_AGENT_NAME=docker-01-build4
      - AZP_POOL=Testing linux docker
    volumes:
      - /opt/Agents/docker-01-build4:/opt/Agents/docker-01-build4
    secrets:
      - azure_pat_token
    restart: always

  agent2:
    build:
      context: .
      dockerfile: azure-agent-linux.dockerfile
    environment:
      - AZP_URL=https://dev.azure.com/krossk
      - AZP_AGENT_NAME=docker-02-build4
      - AZP_POOL=Testing linux docker
    volumes:
      - /opt/Agents/docker-02-build4:/opt/Agents/docker-02-build4
    secrets:
      - azure_pat_token
    restart: always

  agent3:
    build:
      context: .
      dockerfile: azure-agent-linux.dockerfile
    environment:
      - AZP_URL=https://dev.azure.com/krossk
      - AZP_AGENT_NAME=docker-03-build4
      - AZP_POOL=Testing linux docker
    volumes:
      - /opt/Agents/docker-03-build4:/opt/Agents/docker-03-build4
    secrets:
      - azure_pat_token
    restart: always

secrets:
  azure_pat_token:
    external: true 
