version: '3.8'

services:
  agent1:
    image: azure-agent-linux:latest
    environment:
      - AZP_URL=https://dev.azure.com/krossk
      - AZP_AGENT_NAME=docker-01-build4
      - AZP_POOL=Testing linux docker
      - KUBECONFIG=/opt/Agents/docker-01-build4/kubeconfig
      - DEVEXTREME_KEY=${DEVEXTREME_KEY}
      - LANG=sk_SK.UTF-8
      - LANGUAGE=sk_SK:sk
      - LC_ALL=sk_SK.UTF-8
      - TZ=Europe/Bratislava
    volumes:
      # - /opt/Agents/docker-01-build4:/opt/Agents/docker-01-build4 # Ak by sme potrebovali uchovavat workspaces aj po ukonceni kontajneru.
      - /opt/Agents/cache:/opt/Agents/cache
    secrets:
      - azure_pat_token
    deploy:
      restart_policy:
        condition: any

  agent2:
    image: azure-agent-linux:latest
    environment:
      - AZP_URL=https://dev.azure.com/krossk
      - AZP_AGENT_NAME=docker-02-build4
      - AZP_POOL=Testing linux docker
      - KUBECONFIG=/opt/Agents/docker-02-build4/kubeconfig
      - DEVEXTREME_KEY=${DEVEXTREME_KEY}
      - LANG=sk_SK.UTF-8
      - LANGUAGE=sk_SK:sk
      - LC_ALL=sk_SK.UTF-8
      - TZ=Europe/Bratislava
    volumes:
      # - /opt/Agents/docker-02-build4:/opt/Agents/docker-02-build4 # Ak by sme potrebovali uchovavat workspaces aj po ukonceni kontajneru.
      - /opt/Agents/cache:/opt/Agents/cache
    secrets:
      - azure_pat_token
    deploy:
      restart_policy:
        condition: any

  agent3:
    image: azure-agent-linux:latest
    environment:
      - AZP_URL=https://dev.azure.com/krossk
      - AZP_AGENT_NAME=docker-03-build4
      - AZP_POOL=Testing linux docker
      - KUBECONFIG=/opt/Agents/docker-03-build4/kubeconfig
      - DEVEXTREME_KEY=${DEVEXTREME_KEY}
      - LANG=sk_SK.UTF-8
      - LANGUAGE=sk_SK:sk
      - LC_ALL=sk_SK.UTF-8
      - TZ=Europe/Bratislava
    volumes:
      # - /opt/Agents/docker-03-build4:/opt/Agents/docker-03-build4 # Ak by sme potrebovali uchovavat workspaces aj po ukonceni kontajneru.
      - /opt/Agents/cache:/opt/Agents/cache
    secrets:
      - azure_pat_token
    deploy:
      restart_policy:
        condition: any

secrets:
  azure_pat_token:
    external: true 
