apiVersion: v1
kind: ConfigMap
metadata:
  name: build-agent-config-build-be
data:
  AZP_URL: "https://dev.azure.com/krossk"
  AZP_POOL: "Build BE"
  DEVEXTREME_KEY: "${DEVEXTREME_KEY}"
  AzurePS: "3.0.1"
# --- 2. spôsob ako vytvoriť secret s PAT tokenom
# apiVersion: v1
# kind: Secret
# metadata:
#   name: azure-pat-token
# type: Opaque
# data:
#   AZURE_PAT_TOKEN: ${AZURE_PAT_TOKEN_BASE64}  # Treba zakódovať PAT token do base64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-be
  labels:
    app: build-agent-build-be
    pool: build-be
spec:
  replicas: 2
  selector:
    matchLabels:
      app: build-agent-build-be
      pool: build-be
  template:
    metadata:
      labels:
        app: build-agent-build-be
        pool: build-be
    spec:
      containers:
      - name: build-be-container
        image: azure-agent-linux:k8s
        env:
        - name: AZP_AGENT_NAME
          value: "$(metadata.name)-build4"
        - name: KUBECONFIG
          value: "/opt/Agents/$(metadata.name)-build4/kubeconfig"
        envFrom:
        - configMapRef:
            name: build-agent-config-build-be
        - secretRef:
            name: azure-pat-token
        # resources:
        #   requests:
        #     cpu: "500m"
        #     memory: "1Gi"
        volumeMounts:
        - name: agent-cache
          mountPath: /opt/Agents/cache
      volumes:
      - name: agent-cache
        persistentVolumeClaim:
          claimName: agent-cache-pvc
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: build-be-scaledObject
spec:
  scaleTargetRef:
    name: build-be
    kind: Deployment
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 2
  maxReplicaCount: 4
  triggers:
  - type: azure-pipelines
    metadata:
      poolName: "Build BE"
      organizationURLFromEnv: "AZP_URL"
      personalAccessTokenFromEnv: "AZURE_PAT_TOKEN"
      targetPipelinesQueueLength: "1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-cache-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard