apiVersion: v1
kind: ConfigMap
metadata:
  name: build-agent-config-common
data:
  AZP_URL: "https://dev.azure.com/krossk"
  AzurePS: "3.0.1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-cache-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard 
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-pipelines-trigger-auth
spec:
  secretTargetRef:
    - parameter: personalAccessToken
      name: azure-pat-token
      key: AZURE_PAT_TOKEN 