apiVersion: v1
kind: ConfigMap
metadata:
  name: build-agent-config-testing-linux-docker
data:
  AZP_POOL: "Testing linux docker"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: testing-linux-docker-deployment
  labels:
    app: build-agent-testing-linux-docker-deployment
    pool: testing-linux-docker
spec:
  serviceName: testing-linux-docker-service
  replicas: 2
  ordinals:
    - start: 1
  selector:
    matchLabels:
      app: build-agent-testing-linux-docker
      pool: testing-linux-docker
  template:
    metadata:
      labels:
        app: build-agent-testing-linux-docker
        pool: testing-linux-docker
    spec:
      containers:
      - name: testing-linux-docker-container
        image: azure-agent-linux:k8s
        env:
        - name: AZP_AGENT_NAME
          value: "$(metadata.name)-build4"
        - name: KUBECONFIG
          value: "/opt/Agents/$(AZP_AGENT_NAME)/kubeconfig"
        envFrom:
        - configMapRef:
            name: build-agent-config-common
        - configMapRef:
            name: build-agent-config-testing-linux-docker
        - secretRef:
            name: azure-pat-token # TODO: Overiť či dokážem pristúpiť v start-k8s.sh v kontajneri na secret.
        volumeMounts:
        - name: agent-cache
          mountPath: /opt/Agents/cache
      volumes:
      - name: agent-cache
        persistentVolumeClaim:
          claimName: agent-cache-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: testing-linux-docker-service
spec:
  clusterIP: None
  selector:
    app: build-agent-testing-linux-docker
    pool: testing-linux-docker
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: testing-linux-docker-scaledObject
spec:
  scaleTargetRef:
    name: testing-linux-docker-deployment
    kind: StatefulSet
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 2
  maxReplicaCount: 4
  triggers:
  - type: azure-pipelines
    metadata:
      poolName: "Testing linux docker"
      organizationURLFromEnv: "AZP_URL"
      targetPipelinesQueueLength: "1"
    authenticationRef:
      name: azure-pipelines-trigger-auth
