# # Spoločné hodnoty pre všetky pooly
# common:
#   azpUrl: "https://dev.azure.com/krossk"
#   azurePS: "3.0.1"
#   storage:
#     class: "standard"
#     size: "100Gi"
#     accessMode: "ReadWriteMany"

# # Predvolené hodnoty pre pool
# pool:
#   name: "default-pool"  # Predvolená hodnota, musí byť prepísaná v values-*.yaml
#   replicas: 2
#   minReplicas: 2
#   maxReplicas: 4
#   pollingInterval: 30
#   cooldownPeriod: 300
#   targetPipelinesQueueLength: "1"
#   image:
#     repository: azure-agent-linux
#     tag: k8s
#     pullPolicy: IfNotPresent

# # Predvolené hodnoty pre secrets
# secrets:
#   azurePatToken:
#     name: azure-pat-token
#     key: AZURE_PAT_TOKEN
#   devextremeKey:
#     name: devextreme-key
#     key: DEVEXTREME_KEY