pool:
  name: "Deploy BE"
  agentNameBase: "deploy-be"
  buildMachineName: "build4"
  replicas: 3
  scaler:
    minReplicas: 4
    maxReplicas: 6
    pollingInterval: 30
    cooldownPeriod: 3600
    targetPipelinesQueueLength: "3"
  image:
    repository: krossk.azurecr.io/azure-agent-linux
    tag: k8s
