pool:
  name: "Build FE"
  agentNameBase: "build-fe"
  replicas: 2
  scaler:
    minReplicas: 2
    maxReplicas: 3
    pollingInterval: 30
    cooldownPeriod: 3600
    targetPipelinesQueueLength: "3"
  image:
    repository: krossk.azurecr.io/azure-agent-linux
    tag: k8s
