pool:
  name: "Testing linux docker"
  agentNameBase: "testing-linux-docker"
  replicas: 4
  scaler:
    minReplicas: 4
    maxReplicas: 5
    pollingInterval: 30
    cooldownPeriod: 3600
    targetPipelinesQueueLength: "1"
  image:
    repository: krossk.azurecr.io/azure-agent-linux
    tag: k8sTesting