pool:
  name: "Deploy BE"
  agentNameBase: "deploy-be"
  replicas: 3
  scaler:
    minReplicas: 3
    maxReplicas: 6
    pollingInterval: 30
    cooldownPeriod: 3600
    targetPipelinesQueueLength: "4"
  image:
    repository: krossk.azurecr.io/azure-agent-linux
    tag: k8s
