pool:
  name: "Ssw-CypressTests"
  agentNameBase: "ssw3-cy"
  replicas: 2
  scaler:
    minReplicas: 4
    maxReplicas: 10
    pollingInterval: 30
    cooldownPeriod: 3600
    targetPipelinesQueueLength: "2"
  image:
    repository: krossk.azurecr.io/azure-agent-linux-cy
    tag: 0.0.7
