pool:
  name: "Deploy FE"
  agentNameBase: "deploy-fe"
  replicas: 1
  scaler:
    minReplicas: 1
    maxReplicas: 2
    pollingInterval: 30
    cooldownPeriod: 3600
    targetPipelinesQueueLength: "1"
  image:
    repository: krossk.azurecr.io/azure-agent-linux
    tag: k8s
