pool:
  name: "Testing linux docker"
  agentNameBase: "testing-linux-docker"
  replicas: 2
  scaler:
    minReplicas: 2
    maxReplicas: 4
    pollingInterval: 30
    cooldownPeriod: 300
    targetPipelinesQueueLength: "1"
  image:
    name: azure-agent-linux
    tag: k8s
