pool:
  name: "Build BE"
  agentNameBase: "build-be"
  replicas: 2
  scaler:
    minReplicas: 2
    maxReplicas: 4
    pollingInterval: 30
    cooldownPeriod: 3600
    targetPipelinesQueueLength: "1"
  image:
    repository: krossk.azurecr.io/azure-agent-linux
    tag: k8s
