apiVersion: batch/v1
kind: Job
metadata:
  name: moj-job-echo
spec:
  template:
    spec:
      containers:
      - name: echo
        image: busybox
        command: ["echo"]
        args: ["I am job."]
      restartPolicy: OnFailure
