apiVersion: v1
kind: Pod
metadata:
  name: moj-data-pod
  labels:
    app: moja-app
spec:
  containers:
    - name: frontend
      image: nginx:latest
      volumeMounts:
        - name: frontend-pod
          mountPath: /var/www/html
  volumes:
    - name: frontend-pod
      persistentVolumeClaim:
        claimName: moj-pvc
